version: "3.5"
services:
  authority:
    image: 5minds/authority:3.0.0-develop-14d179-ljzpzplf
    ports:
      - 11560:11560
    volumes:
      - ./.processcube/authority/config.json:/etc/authority/config/config.json:ro
      - ./.processcube/authority/users.json:/etc/authority/config/users.json
    environment:
      AdminCli__AdministratorRole: Administrators
